/****************************************************/
/*********   Author    : Mariz Mamdouh     **********/
/*********   Date      : 1 Oct 2023        **********/
/*********   Version   : 0.1               **********/
/*********   File name : USART_interface.h **********/
/****************************************************/
#ifndef USART_INTERFACE_H
#define USART_INTERFACE_H

/**
 * @addtogroup UART_Configuration_Options
 * @{
 */
#define USART_CLK_SRC   8000000

/**
 * @brief Enumeration of UART hardware flow control options.
 *
 * This enumeration defines the possible hardware flow control options that can be used in UART communication.
 * Hardware flow control helps manage the flow of data between the sender and receiver to prevent data overrun or loss.
 * The options include:
 *
 * - USART_HW_FLOW_CONTROL_NONE: No hardware flow control. Data transmission is not controlled by additional signals.
 * - USART_HW_FLOW_CONTROL_RTS: Request to Send (RTS) hardware flow control. The transmitter asserts the RTS signal
 *   to indicate that it is ready to send data, and the receiver uses RTS as an indication that it can receive data.
 *   Data transmission occurs only when RTS is asserted.
 * - USART_HW_FLOW_CONTROL_CTS: Clear to Send (CTS) hardware flow control. The receiver asserts the CTS signal to
 *   indicate that it is ready to accept data, and the transmitter uses CTS as an indication that it can start
 *   transmitting data. Data transmission occurs only when CTS is asserted.
 * - USART_HW_FLOW_CONTROL_RTS_CTS: RTS and CTS hardware flow control. Both RTS and CTS signals are used for flow control,
 *   allowing bidirectional control of data transmission. The transmitter uses RTS to indicate readiness, and the receiver
 *   uses CTS to indicate readiness to receive data.
 *
 * @note RTS (Request to Send): RTS is an output signal generated by the data sender (transmitter) to the data receiver.
 * When the transmitter has data to send and is ready to transmit, it asserts the RTS signal to inform the receiver
 * that it is ready to send data. The receiver uses the RTS signal as an indication that it can receive data.
 * Data transmission occurs only when the RTS signal is asserted.
 *
 * @note CTS (Clear to Send): CTS is an input signal generated by the data receiver to the data sender (transmitter).
 * When the receiver is ready to receive data, it asserts the CTS signal to inform the transmitter that it is ready
 * to accept data. The transmitter uses the CTS signal as an indication that it can start transmitting data.
 * Data transmission occurs only when the CTS signal is asserted.
 */
typedef enum{
    USART_HW_FLOW_CONTROL_NONE,
    USART_HW_FLOW_CONTROL_RTS,
    USART_HW_FLOW_CONTROL_CTS,
    USART_HW_FLOW_CONTROL_RTS_CTS
}USART_HW_FlowControl_t;

typedef struct{
    u8 HwFlowControl:2;
    u8 ParityMode:2;
    u8 BaudRate:2;
    u8 StopBits:2;
    u8 DataBit:1;
    u8:7;
}USART_Config_t

Std_ReturnType MCAL_USART_Init(USART_Config_t *Copy_USARTConfig);

/**
 * @}
 */

#endif /**< USART_INTERFACE_H */
